# Change these first
owner: jawaracloud # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Landing Page
    url: https://jawara.cloud
    expectedStatusCodes:
      - 200
  - name: The Overflow Bot
    url: https://the-overflow-bot.jawaracloud.workers.dev/ping
    expectedStatusCodes:
      - 200
  - name: Landing Page Jawara Group
    url: https://jawaragroup.co
    expectedStatusCodes:
      - 200
  - name: Landing Page Teman Hanan
    url: https://hanan.live
    expectedStatusCodes:
      - 200
  - name: Islamic Wedding Invitation Website
    url: https://islamic-wedding-invitation.vercel.app/
    expectedStatusCodes:
      - 200
    
assignees: # Users to assign downtime issues (optional)
  - mrofisr
  
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.jawara.cloud
  logoUrl: https://raw.githubusercontent.com/jawaracloud/.github/b9cb60aeb27a9c0a6ea8b49f3c60d68565dbd847/jawara.svg
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  name: ""
  favicon: https://raw.githubusercontent.com/jawaracloud/.github/b9cb60aeb27a9c0a6ea8b49f3c60d68565dbd847/jawara.svg
  faviconSvg: https://raw.githubusercontent.com/jawaracloud/.github/b9cb60aeb27a9c0a6ea8b49f3c60d68565dbd847/jawara.svg
  introMessage: This is a uptime page Jawara Cloud Service
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/jawaracloud
    - title: Website
      href: https://jawara.cloud

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
